### ISSUE TITLE
Routing not possible due to "Uncaught TypeError: k.stations is not a function"

### ISSUE THREAD

**Issue by yannickoo** [derhuerst/vbb-map-routing#40]
It seems like the autocomplete doesn't work atm because of this error

> `Uncaught TypeError: k.stations is not a function in bundle.js`

**Comment by derhuerst** [comment]
Cannot reproduce it. Can you give more specific instructions how to make this error appear?

**Comment by derhuerst** [comment]
I'm going to close this. Please re-open if you encounter this issue again.
